### ISSUE TITLE
Request for load more feature

### ISSUE THREAD

**Issue by BolajiAyodeji** [Hashnode/hashnode-browser-extensions#3]
Currently, the extension displays just Five (5) recent articles for both HOT DISCUSSIONS and TRENDING STORIES.

![image](https://user-images.githubusercontent.com/30334776/59152481-8d038600-8a3c-11e9-9ce7-4db9017b3ef0.png)

I would love to see a load more button, so a user can request for five more articles per each button click.

Is this visible?

**Comment by BolajiAyodeji** [comment]
Anyone reviewing this?

**Comment by BolajiAyodeji** [comment]
Any updates to this please?

**Comment by theevilhead** [comment]
The feature is implemented. Should be live by tomorrow.

**Comment by BolajiAyodeji** [comment]
Thank you @theevilhead, It's live already.
Closing this now.
